### ISSUE TITLE
جواب سوالات به زبان سی‌شارپ

### ISSUE THREAD

**Issue by HamidMolareza** [MohammadNPak/quera.ir#2]
سلام
منم جواب سوالاتی (که به مرور) حل میکنم رو توی این [مخزن](https://github.com/HamidMolareza/QueraProblems) قرار میدم.

[مخزن شما](https://github.com/HamidMolareza/QueraProblems#related) رو هم اضافه کردم.

زبون اصلی سی‌شارپ هستش. اگر کسی لازم داشت لطفا بهش معرفی کنید.

ممنون.

**Comment by MohammadNPak** [comment]
سلام. متشکر از زحمت شما. البته توی همین مخزن فعلی امکان اضافه کردن راه حل به با هر زبانی امکان پذیر هست. اگر مایل بودید اینجا هم قرار بدید کدتونو و اگر از کدی که اینجا نوشته شده استفاده کردید حتما داخل کد رفرنس به همین مخزن بدید. باتشکر.
